journals:
  - underworld-community/uwc-reviews-testing:
      editor_team_id: 3262530
      eics:
        - rbeucher
      papers: underworld-community/uwc-models-testing
      reviewers: https://bit.ly/joss-reviewers
      reviewers_signup: http://joss.theoj.org/reviewer-signup.html
      site_host: http://joss.theoj.org
      doi_prefix: "10.21105"
      journal_alias: joss
      journal_launch_date: '2016-05-05'
      site_name: Journal of Open Source Software
      donate_url: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
      site_api_key: <%= ENV['UWC_API_KEY'] %>
