journals:
  - underworld-community/uwc-reviews:
      editor_team_id: 3262530
      eics:
        - rbeucher
      eic_team_name: underworld-community/editors
      papers_repo: underworld-community/uwc-models
      reviewers: "https://bit.ly/2XC2Z9e"
      reviewers_signup: https://underworld-community.herokuapp.com/reviewer-signup.html
      site_host: https://underworld-community.herokuapp.com
      doi_prefix: "10.6666"
      journal_alias: uwc
      journal_launch_date: '2021-10-01'
      journal_issn: '0000-0000'
      site_name: Underworld Community
      site_api_key: <%= ENV['UWC_API_KEY'] %>
      twitter_consumer_key: <%= ENV['UWC_TWITTER_CONSUMER_KEY'] %>
      twitter_consumer_secret: <%= ENV['UWC_TWITTER_CONSUMER_SECRET'] %>
      twitter_access_token: <%= ENV['UWC_TWITTER_ACCESS_TOKEN'] %>
      twitter_access_token_secret: <%= ENV['UWC_TWITTER_ACCESS_TOKEN_SECRET'] %>