journals:
  - openjournals/joss-reviews:
      editor_team_id: 2009411
      eics:
        - rbeucher
      eic_team_name: underworld-community/editors
      papers_repo: underworld-community/uwc-models
      reviewers: https://bit.ly/joss-reviewers
      reviewers_signup: https://joss.theoj.org/reviewer-signup.html
      site_host: https://joss.theoj.org
      doi_prefix: "10.21105"
      journal_alias: joss
      journal_launch_date: '2016-05-05'
      journal_issn: '2475-9066'
      site_name: Journal of Open Source Software
      donate_url: https://numfocus.org/donate-to-joss
      site_api_key: <%= ENV['UWC_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>
      twitter_consumer_key: <%= ENV['JOSS_TWITTER_CONSUMER_KEY'] %>
      twitter_consumer_secret: <%= ENV['JOSS_TWITTER_CONSUMER_SECRET'] %>
      twitter_access_token: <%= ENV['JOSS_TWITTER_ACCESS_TOKEN'] %>
      twitter_access_token_secret: <%= ENV['JOSS_TWITTER_ACCESS_TOKEN_SECRET'] %>