journals:
  - underworld-community/uwc-reviews:
      editor_team_id: 3262530
      eics:
        - rbeucher
      papers: underworld-community/uwc-models-testing
      reviewers: "https://bit.ly/2XC2Z9e"
      reviewers_signup: https://underworld-community.herokuapp.com/reviewer-signup.html
      site_host: https://underworld-community.herokuapp.com/
      doi_prefix: "10.66666"
      journal_alias: uwc
      journal_launch_date: '2021-10-01'
      site_name: Underworld Community
      site_api_key: <%= ENV['UWC_API_KEY'] %>
